/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Richard' at '1/30/16 1:10 PM' with Gradle 2.3
 *
 * @author Richard, @date 1/30/16 1:10 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
